### PR TITLE
Fix most of the issues and test cases (see description)

### LINKED ISSUE #43: Warnings with newer Emacs versions
With Emacs 28, I get the following warnings:
```
path/to/pcre2el.el: Warning: Use keywords rather than deprecated positional arguments to `define-minor-mode' [2 times]
path/to/pcre2el.el: Warning: ‘merge’ is an obsolete alias (as of 27.1); use ‘cl-merge’ instead.
```

### PR DESCRIPTION
**Pull request by LemonBreezes**
This PR fixes #43, #41, #39, and partially addresses #40 by fixing most of the test cases. Now only 7/1093 of the test cases fail. I also made a few fixes that have not been reported as issues yet.

I believe that the remaining test cases need to be reviewed because some of them (I believe) are being executed correctly but the expected result is incorrect.

### CODE REVIEW

**Comment by LemonBreezes** [comment]
Since I have added a dependency on `a.el`, I need to fix the Makefile.

**Comment by dogsleg** [comment]
Cool! I can confirm that almost all issues are solved in this PR. Looks like the current maintainer is not active anymore, so I guess, @LemonBreezes, you could either try to contact them and ask about transition of maintenance in case it is OK with your plans, or just fork the package and continue its development separately.

**Comment by hardaker** [comment]
So it turns out that @joddie gave me write access to the repository so I was able to do the merge.  Thanks for all the hard work.

**Comment by dogsleg** [comment]
@hardaker, thanks for your work on it! And thanks to @joddie! Since PR #42 bumping version number is merged now it would be great if you tag the current state as 1.9. Thanks again!

**Pull request merged**
